### ISSUE TITLE
Can't load model name

### ISSUE THREAD

**Issue by ShineHe2023** [GreenLandisaLie/AuraSR-ComfyUI#6]
![Snipaste_2024-07-03_09-21-11](https://github.com/GreenLandisaLie/AuraSR-ComfyUI/assets/126451667/bbebfa3b-c417-49c7-a56e-7173a3371c21)
Instructions:
Create a folder named 'Aura-SR' inside '\models'.
Download the .safetensors AND config.json files from [HuggingFace](https://huggingface.co/fal/AuraSR/tree/main) and place them in '\models\Aura-SR'

**Comment by GreenLandisaLie** [comment]
Reload the page. If that still doesn't work then reload ComfyUI entirely.

**Comment by ShineHe2023** [comment]
> Reload the page. If that still doesn't work then reload ComfyUI entirely.
> 
> EDIT: Just tried it out. So long as you don't have any node that's not changing ComfyUI's internal 'models' path - this can only happen if you add the AuraSR node before adding the models to the Aura-SR folder. Once the models are in there, you only need to reload the browser's page and click on the white arrow '>' to select the model. At this point, the model will be selected by default on newly added AuraSR nodes.

I restart ComfyUI many times,and refreshed browser many times, but it doesn't work

**Comment by lonmusk** [comment]
I have the same trouble

**Comment by mvstrawn** [comment]
Same issue. I restarted everything, uninstalled/reinstalled the plugin (I had not followed the installation order and installed the node prior to creating the /models/Aura-SR/ folder), restarted again.

But I fixed it!

In nodes.py,
```
folder_paths.folder_names_and_paths["aura-sr"] = ([os.path.join(folder_paths.models_dir, "aura-sr")], folder_paths.supported_pt_extensions)
```
is looking for 'aura-sr', not 'Aura-SR'. I am on Arch Linux, where pathing is case sensitive. Changing the folder name to lower case fixed it.

**Comment by GreenLandisaLie** [comment]
@mvstrawn 
Thank you for the insights. If it works on some OSs and not on others then this is a Python issue in my opinion. I'll fix it right away. Hopefully it works for OP too even though he seems to be on Windows.

**Comment by GreenLandisaLie** [comment]
@ShineHe2023, @lonmusk
I've updated with a fix for case sensitive pathing. Please install the latest version following a ComfyUI restart then refresh the browser's page and delete any AuraSR node that shows up by default from your cache - if they show up. Add a new AuraSR node and check if its working properly now.

IF its still not working then I need to check your paths for anything that may be causing an issue and for that I need you to do the following:
- Open '...\custom_nodes\AuraSR-ComfyUI\nodes.py' with a Text Editor.
- Find the line 'folder_paths.folder_names_and_paths["aura-sr"] = ([aurasr_fullpath], folder_paths.supported_pt_extensions)' at the top.
- Right bellow it, add the following lines:
```
## DEBUG ------
print("\n\n\n[AuraSR-ComfyUI] Debugging paths...")
print(f"folder_paths.folder_names_and_paths['aura-sr']: {folder_paths.folder_names_and_paths['aura-sr']}")
try:
    print(f"aura-sr dir detected: {os.path.exists(folder_paths.folder_names_and_paths['aura-sr'][0][0]) and os.path.isdir(folder_paths.folder_names_and_paths['aura-sr'][0][0])}")
    print(f"Models inside \Aura-SR obtained by ComfyUI's 'get_filename_list' function: {folder_paths.get_filename_list('aura-sr')}")
    print(f"All files in \Aura-SR: {[str(f).replace(folder_paths.folder_names_and_paths['aura-sr'][0][0], '') for f in Path(folder_paths.folder_names_and_paths['aura-sr'][0][0]).rglob('*') if f.is_file()]}")
except:
    print("Invalid Aura-SR location.")
    pass
print("[AuraSR-ComfyUI] Finished debugging paths.\n\n\n")
## DEBUG ------
```
- Save the file.
- Start/Restart ComfyUI
- Keep an eye on the terminal and copy the lines from '[AuraSR-ComfyUI] Debugging paths...' to '[AuraSR-ComfyUI] Finished debugging paths.'
- Post them here so I can inspect them.

**Comment by GreenLandisaLie** [comment]
Closing this under the assumption it has already been fixed in the latest update.
